"""Message foreign key

Revision ID: 4cde2e2895e1
Revises: 29d677c8ab2c
Create Date: 2019-05-05 22:17:25.721204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cde2e2895e1'
down_revision = '29d677c8ab2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    # ### end Alembic commands ###
